name:                 FormValidation
highlighter:          pygments

source:               .
destination:          ../output
markdown:             kramdown
exclude:              ['node_modules', '*.less', '*.programmatic', '*.declarative', '*.markup', '*.md', '.gitignore', 'Gemfile']
url:                  http://formvalidation.io

paginate:             5
paginate_path:        /news/page:num
encoding:             UTF-8
relative_permalinks:  false
permalink:            /news/:title/
timezone:             Asia/Ho_Chi_Minh

gems:
  - jekyll-sitemap

# Custom variables
# not defined by Jekyll
description:          FormValidation - The best jQuery plugin to validate form fields, support Bootstrap, Foundation, Pure, Semantic, UIKit frameworks
license:
  developer:
    price:            25$
    gumroad_url:      https://gum.co/formvalidation-developer-license
    sellfy_url:       https://sellfy.com/p/uitF/
    sellfy_id:        uitF
  organization:
    price:            75$
    gumroad_url:      https://gum.co/formvalidation-organization-license
    sellfy_url:       https://sellfy.com/p/eQiZ/
    sellfy_id:        eQiZ
current_version:      0.6.2
released_date:        2015.04.02
num_downloads:        100000
support:              https://github.com/formvalidation/support/issues
ga_code:              UA-44786951-2